services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextgoa_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - /opt/next/NextGoa/public/uploads:/app/public/uploads
      - /opt/next/NextGoa/goa-uploads:/app/goa-uploads
    depends_on:
      - db
    networks:
      - project_network

  db:
    image: mysql:8.0
    container_name: nextgoa_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: nextgoa_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
      PMA_ABSOLUTE_URI: "https://goa.paruluniversity.ac.in/phpmyadmin/"
    depends_on:
      - db
    networks:
      - project_network

volumes:
  mysql_data:

networks:
  project_network:
    driver: bridge